# Generated by Django 2.2.4 on 2019-10-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarea4', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistorialDeActividades',
            new_name='Actividad',
        ),
    ]
