# Generated by Django 2.2.6 on 2019-10-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea4', '0003_auto_20191020_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='test',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
