# Generated by Django 2.2.6 on 2019-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea4', '0004_usuario_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='test',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='fotitos'),
        ),
    ]
